### PR TITLE
Show list name on Poll Card

### PR DESCRIPTION
**Pull request by filg68**

### CODE REVIEW

**Comment by IoPhoenix** [comment]
Add the same to Poll Page and check if it works with the newly created poll

**Comment by filg68** [comment]
> Add the same to Poll Page and check if it works with the newly created poll

Checked when creating new poll and when loading data on startup.  List name is successfully displayed.

**Comment by IoPhoenix** [comment]
How about PollPage? Will you open a separate issue for that?

**Comment by filg68** [comment]
> How about PollPage? Will you open a separate issue for that?

I will make change to this PR and add it.

**Pull request merged**
